name: pokedex
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: 6.2.1
  hooks_riverpod: 2.5.1
  flutter_hooks: 0.20.5
  auto_route: 8.0.0
  flutter_svg: 2.0.10+1
  logger: any
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0
  collection: 1.18.0
  gap: 3.0.1
  shimmer: 3.0.0
  http: 1.2.1
  shared_preferences: 2.2.3
  flutter_slidable: 3.1.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.11
  flutter_gen_runner:
  auto_route_generator: 8.0.0
  freezed: 2.5.2
  json_serializable: 6.8.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/images/